// <auto-generated />
using System;
using BotCarlaREST.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BotCarlaREST.Migrations
{
    [DbContext(typeof(Datasql))]
    [Migration("20230217101318_friday_carla")]
    partial class friday_carla
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.13")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BotCarlaREST.Models.Raid", b =>
                {
                    b.Property<int>("RaidId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RaidId"), 1L, 1);

                    b.Property<DateTime>("Raiddate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Raidname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tier")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RaidId");

                    b.ToTable("raid");
                });

            modelBuilder.Entity("BotCarlaREST.Models.Raiduser", b =>
                {
                    b.Property<int>("UserDId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserDId"), 1L, 1);

                    b.Property<int?>("RaidId")
                        .HasColumnType("int");

                    b.Property<string>("UserDName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserDId");

                    b.HasIndex("RaidId");

                    b.ToTable("Raiduser");
                });

            modelBuilder.Entity("BotCarlaREST.Models.Raiduser", b =>
                {
                    b.HasOne("BotCarlaREST.Models.Raid", null)
                        .WithMany("Raidusers")
                        .HasForeignKey("RaidId");
                });

            modelBuilder.Entity("BotCarlaREST.Models.Raid", b =>
                {
                    b.Navigation("Raidusers");
                });
#pragma warning restore 612, 618
        }
    }
}
